### ISSUE TITLE
`GeekDetails`'s modal is not configured to work in dark mode

### ISSUE THREAD

**Issue by adriancuadrado** [tigera/docs#1780]
https://github.com/tigera/docs/blob/45b547a91b6901fce2e6e266fe7683ed63d6dc8a/calico_versioned_docs/version-3.29/getting-started/kubernetes/quickstart.mdx?plain=1#L50-L53

This is how the popup is rendered in [the website](https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart) when using dark mode:

![image](https://github.com/user-attachments/assets/6013c730-d9e1-43ac-8bd9-820be2796351)

I have to select the text to be able to read it:

![image](https://github.com/user-attachments/assets/3ac8f62c-adc6-4adb-829d-2c990481b03f)

**Comment by ctauchen** [comment]
FYI @ronanc-tigera

**Comment by ronanc-tigera** [comment]
@ctauchen fix is live 
![image](https://github.com/user-attachments/assets/852c8240-8a94-4efc-a498-b300eeb690cc)

**Comment by ctauchen** [comment]
@ronanc-tigera Thanks!
